### ISSUE TITLE
In function ‘void* soapysdr_rx_thread  - Can't make for soapySDR

### ISSUE THREAD

**Issue by rapbando** [szpajder/RTLSDR-Airband#181] opened 2020-08-13 21:21 UTC
I'm getting this input converison errors while trying to make for my HackRF and soapy library.

```
radar@radar:~/RTLSDR-Airband-3.1.0$ make PLATFORM=x86 WITH_RTLSDR=0 WITH_SOAPYSDR=1
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o rtl_airband.o rtl_airband.cpp
rtl_airband.cpp: In function ‘int main(int, char**)’:
rtl_airband.cpp:825:26: warning: catching polymorphic type ‘class libconfig::FileIOException’ by value [-Wcatch-value=]
  825 |  } catch(FileIOException e) {
      |                          ^
rtl_airband.cpp:828:25: warning: catching polymorphic type ‘class libconfig::ParseException’ by value [-Wcatch-value=]
  828 |  } catch(ParseException e) {
      |                         ^
rtl_airband.cpp:831:35: warning: catching polymorphic type ‘class libconfig::SettingNotFoundException’ by value [-Wcatch-value=]
  831 |  } catch(SettingNotFoundException e) {
      |                                   ^
rtl_airband.cpp:834:31: warning: catching polymorphic type ‘class libconfig::SettingTypeException’ by value [-Wcatch-value=]
  834 |  } catch(SettingTypeException e) {
      |                               ^
rtl_airband.cpp:837:26: warning: catching polymorphic type ‘class libconfig::ConfigException’ by value [-Wcatch-value=]
  837 |  } catch(ConfigException e) {
      |                          ^
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o input-common.o input-common.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o input-helpers.o input-helpers.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o output.o output.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o config.o config.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o util.o util.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o mixer.o mixer.cpp
g++ -O3 -g -Wall -DSYSCONFDIR=\"/usr/local/etc\" -DDEBUG=0 -march=native -DWITH_SOAPYSDR   -c -o input-soapysdr.o input-soapysdr.cpp
input-soapysdr.cpp: In function ‘void* soapysdr_rx_thread(void*)’:
input-soapysdr.cpp:315:37: error: invalid conversion from ‘SoapySDRStream**’ to ‘int’ [-fpermissive]
  315 |  if(SoapySDRDevice_setupStream(sdr, &rxStream, SOAPY_SDR_RX, dev_data->sample_format,
      |                                     ^~~~~~~~~
      |                                     |
      |                                     SoapySDRStream**
In file included from /usr/local/include/SoapySDR/Device.h:20,
                 from input-soapysdr.cpp:29:
input-soapysdr.cpp:315:48: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
  315 |  if(SoapySDRDevice_setupStream(sdr, &rxStream, SOAPY_SDR_RX, dev_data->sample_format,
      |                                                ^~~~~~~~~~~~
      |                                                |
      |                                                int
input-soapysdr.cpp:315:72: error: cannot convert ‘const char*’ to ‘const size_t*’ {aka ‘const long unsigned int*’}
  315 |  if(SoapySDRDevice_setupStream(sdr, &rxStream, SOAPY_SDR_RX, dev_data->sample_format,
      |                                                              ~~~~~~~~~~^~~~~~~~~~~~~
      |                                                                        |
      |                                                                        const char*
In file included from input-soapysdr.cpp:29:
/usr/local/include/SoapySDR/Device.h:298:19: note:   initializing argument 4 of ‘SoapySDRStream* SoapySDRDevice_setupStream(SoapySDRDevice*, int, const char*, const size_t*, size_t, const SoapySDRKwargs*)’
  298 |     const size_t *channels,
      |     ~~~~~~~~~~~~~~^~~~~~~~
make: *** [<builtin>: input-soapysdr.o] Error 1
```

While soapy seems to be configured properly, see the device status and info under:
```

radar@radar:~/RTLSDR-Airband-3.1.0$ SoapySDRUtil --find
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Found device 0
  device = HackRF One
  driver = hackrf
  label = HackRF One #0 75b068dc32331707
  part_id = a000cb3c0046475b
  serial = 000000000000000075b068dc32331707
  version = 2018.01.1
```

**Comment by szpajder** [comment] 2020-08-13 22:01
Duplicate of https://github.com/szpajder/RTLSDR-Airband/issues/141

**Closed by szpajder** 2020-08-13 22:01 UTC
