### ISSUE TITLE
[BUG] TAGS not Visible when streaming with ICECAST2

### ISSUE THREAD

**Issue by tet024** [szpajder/RTLSDR-Airband#270] opened 2021-08-13 14:28 UTC
Hello, 

I have an issue that the tags aren't visible any longer when streaming with ICECAST. This was working before but suddenly they disappeared. 

      outputs: (

          # For local IceCast server
        {
          disable = false;    
          type = "icecast";
          server = "127.0.0.1";
          port = 8000;
          mountpoint = "stream.mp3";
          name = "Airport_MLA";
          genre = "ATC";
          username = "source";
          password = "xxxxxxxx";
          send_scan_freq_tags = true;
          description = "MLA Aggregated Feed";

any ideas on how to trouble shoot this issue please? 

Thanks, 
Et

**Comment by szpajder** [comment] 2021-08-13 20:18
Which rtl_airband version and libshout version are you using?

**Comment by tet024** [comment] 2021-08-15 17:39
RTLSDR-Airband version v3.2.1-2-gb4335d1
Icecast 2.4.4

**Comment by szpajder** [comment] 2021-08-15 17:52
Icecast server version is irrelevant. Please check the version of libshout
library on the machine where you run rtl_airband.

See also https://github.com/szpajder/RTLSDR-Airband/issues/203

**Comment by tet024** [comment] 2021-08-16 04:44
Good Morning, 

libshout - 2.4.3-1

Thanks, 
Et

**Comment by szpajder** [comment] 2021-08-16 17:21
In this case it's a duplicate of https://github.com/szpajder/RTLSDR-Airband/issues/203

**Closed** 2021-08-16 17:21 UTC
Labels: duplicate
